/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Stikom Bali - 6
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbMakanan = new javax.swing.JComboBox<>();
        CbMinuman = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        LbHargaMak = new javax.swing.JLabel();
        LbHargaMin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TfJumlahMak = new javax.swing.JTextField();
        TfJumlahMin = new javax.swing.JTextField();
        BtnHitung = new javax.swing.JButton();
        LbHasil = new javax.swing.JLabel();
        CbMakanan1 = new javax.swing.JComboBox<>();
        LbHargaMak1 = new javax.swing.JLabel();
        TfJumlahMak1 = new javax.swing.JTextField();
        CbMakanan2 = new javax.swing.JComboBox<>();
        LbHargaMak2 = new javax.swing.JLabel();
        TfJumlahMak2 = new javax.swing.JTextField();
        TfJumlahMak3 = new javax.swing.JTextField();
        CbMakanan3 = new javax.swing.JComboBox<>();
        LbHargaMak3 = new javax.swing.JLabel();
        TfJumlahMak4 = new javax.swing.JTextField();
        CbMakanan4 = new javax.swing.JComboBox<>();
        LbHargaMak4 = new javax.swing.JLabel();
        TfJumlahMin1 = new javax.swing.JTextField();
        CbMinuman1 = new javax.swing.JComboBox<>();
        LbHargaMin1 = new javax.swing.JLabel();
        TfJumlahMin2 = new javax.swing.JTextField();
        CbMinuman2 = new javax.swing.JComboBox<>();
        LbHargaMin2 = new javax.swing.JLabel();
        TfJumlahMin3 = new javax.swing.JTextField();
        CbMinuman3 = new javax.swing.JComboBox<>();
        LbHargaMin3 = new javax.swing.JLabel();
        TfJumlahMin4 = new javax.swing.JTextField();
        CbMinuman4 = new javax.swing.JComboBox<>();
        LbHargaMin4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Makanan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Minuman");

        CbMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakso", "Soto", "Mie", "Capcay" }));
        CbMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMakananActionPerformed(evt);
            }
        });

        CbMinuman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh", "Es Jeruk", "Air Mineral", "Es Kelapa" }));
        CbMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMinumanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Harga");

        LbHargaMak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMak.setText("0");

        LbHargaMin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMin.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah");

        BtnHitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnHitung.setText("Total Belanja");
        BtnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHitungActionPerformed(evt);
            }
        });

        LbHasil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LbHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHasil.setText("0");

        CbMakanan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakso", "Soto", "Mie", "Capcay" }));
        CbMakanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMakanan1ActionPerformed(evt);
            }
        });

        LbHargaMak1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMak1.setText("0");

        CbMakanan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakso", "Soto", "Mie", "Capcay" }));
        CbMakanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMakanan2ActionPerformed(evt);
            }
        });

        LbHargaMak2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMak2.setText("0");

        CbMakanan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakso", "Soto", "Mie", "Capcay" }));
        CbMakanan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMakanan3ActionPerformed(evt);
            }
        });

        LbHargaMak3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMak3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMak3.setText("0");

        CbMakanan4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakso", "Soto", "Mie", "Capcay" }));
        CbMakanan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMakanan4ActionPerformed(evt);
            }
        });

        LbHargaMak4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMak4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMak4.setText("0");

        CbMinuman1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh", "Es Jeruk", "Air Mineral", "Es Kelapa" }));
        CbMinuman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMinuman1ActionPerformed(evt);
            }
        });

        LbHargaMin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMin1.setText("0");

        CbMinuman2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh", "Es Jeruk", "Air Mineral", "Es Kelapa" }));
        CbMinuman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMinuman2ActionPerformed(evt);
            }
        });

        LbHargaMin2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMin2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMin2.setText("0");

        CbMinuman3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh", "Es Jeruk", "Air Mineral", "Es Kelapa" }));
        CbMinuman3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMinuman3ActionPerformed(evt);
            }
        });

        LbHargaMin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMin3.setText("0");

        CbMinuman4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Es Teh", "Es Jeruk", "Air Mineral", "Es Kelapa" }));
        CbMinuman4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbMinuman4ActionPerformed(evt);
            }
        });

        LbHargaMin4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbHargaMin4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbHargaMin4.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(148, 148, 148))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(CbMakanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(113, 113, 113)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(130, 130, 130))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(LbHargaMak, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(118, 118, 118))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CbMinuman1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CbMinuman, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(113, 113, 113)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LbHargaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LbHargaMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LbHargaMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(118, 118, 118)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(TfJumlahMak, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(TfJumlahMin)
                                    .addComponent(TfJumlahMin1)
                                    .addComponent(TfJumlahMin2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CbMakanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(LbHargaMak1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(TfJumlahMak1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CbMakanan2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(LbHargaMak2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(TfJumlahMak2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CbMakanan4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(LbHargaMak4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(TfJumlahMak4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CbMakanan3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(LbHargaMak3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(TfJumlahMak3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnHitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LbHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(LbHargaMin3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(TfJumlahMin3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(LbHargaMin4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(TfJumlahMin4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CbMinuman3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CbMinuman2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CbMinuman4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(356, 356, 356)))))))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TfJumlahMak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CbMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbHargaMak)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbMakanan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMak1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMak2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbMakanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMak2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMak3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbMakanan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMak3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMak4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbMakanan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMak4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(TfJumlahMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbHargaMin))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMin1)
                    .addComponent(CbMinuman1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMin2)
                    .addComponent(CbMinuman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMin3)
                    .addComponent(CbMinuman3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfJumlahMin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbHargaMin4)
                    .addComponent(CbMinuman4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHitung)
                    .addComponent(LbHasil))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMakananActionPerformed
        if (CbMakanan.getSelectedItem()=="Bakso"){
            LbHargaMak.setText("10000");
            
        }
        
        if (CbMakanan.getSelectedItem()=="Soto"){
            LbHargaMak.setText("15000");
        }
        
        if (CbMakanan.getSelectedItem()=="Mie"){
            LbHargaMak.setText("4000");
        }
        
        if (CbMakanan.getSelectedItem()=="Capcay"){
            LbHargaMak.setText("6000");
        }
        
        if (CbMakanan.getSelectedItem() == ""){
            LbHargaMak.setText("0");
        }
    }//GEN-LAST:event_CbMakananActionPerformed

    private void CbMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMinumanActionPerformed
        if (CbMinuman.getSelectedItem()=="Es Teh"){
            LbHargaMin.setText("1500");
        }
        
        if (CbMinuman.getSelectedItem()=="Es Jeruk"){
            LbHargaMin.setText("3000");
        }
        
        if (CbMinuman.getSelectedItem()=="Air Mineral"){
            LbHargaMin.setText("2500");
        }
        
        if (CbMinuman.getSelectedItem()=="Es Kelapa"){
            LbHargaMin.setText("6000");
        }
        
        if (CbMinuman.getSelectedItem()== ""){
            LbHargaMin.setText("0");
        }
    }//GEN-LAST:event_CbMinumanActionPerformed

    private void BtnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHitungActionPerformed
        int hargamak, hargamin, jummakanan, jumminuman, totalbelanja;
        
        hargamak = Integer.parseInt(LbHargaMak.getText());
        hargamak = Integer.parseInt(LbHargaMak1.getText());
        hargamak = Integer.parseInt(LbHargaMak2.getText());
        hargamak = Integer.parseInt(LbHargaMak3.getText());
        hargamak = Integer.parseInt(LbHargaMak4.getText());
        hargamin = Integer.parseInt(LbHargaMin.getText());
        hargamin = Integer.parseInt(LbHargaMin1.getText());
        hargamin = Integer.parseInt(LbHargaMin2.getText());
        hargamin = Integer.parseInt(LbHargaMin3.getText());
        hargamin = Integer.parseInt(LbHargaMin4.getText());
        jummakanan = Integer.parseInt(TfJumlahMak.getText());
        jumminuman = Integer.parseInt(TfJumlahMin.getText());
        totalbelanja=(hargamak*jummakanan) + (hargamin*jumminuman);
        LbHasil.setText(String.valueOf(totalbelanja));
    }//GEN-LAST:event_BtnHitungActionPerformed

    private void CbMakanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMakanan1ActionPerformed
        if (CbMakanan1.getSelectedItem()=="Bakso"){
            LbHargaMak1.setText("10000");
            
        }
        
        if (CbMakanan1.getSelectedItem()=="Soto"){
            LbHargaMak1.setText("15000");
        }
        
        if (CbMakanan1.getSelectedItem()=="Mie"){
            LbHargaMak1.setText("4000");
        }
        
        if (CbMakanan1.getSelectedItem()=="Capcay"){
            LbHargaMak1.setText("6000");
        }
         if (CbMakanan1.getSelectedItem() == ""){
            LbHargaMak1.setText("0");
        }
         
    }//GEN-LAST:event_CbMakanan1ActionPerformed

    private void CbMakanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMakanan2ActionPerformed
        if (CbMakanan2.getSelectedItem()=="Bakso"){
            LbHargaMak2.setText("10000");
            
        }
        
        if (CbMakanan2.getSelectedItem()=="Soto"){
            LbHargaMak2.setText("15000");
        }
        
        if (CbMakanan2.getSelectedItem()=="Mie"){
            LbHargaMak2.setText("4000");
        }
        
        if (CbMakanan2.getSelectedItem()=="Capcay"){
            LbHargaMak2.setText("6000");
        }
    
         if (CbMakanan2.getSelectedItem() == ""){
            LbHargaMak2.setText("0");
        }
    }//GEN-LAST:event_CbMakanan2ActionPerformed

    private void CbMakanan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMakanan3ActionPerformed
        if (CbMakanan3.getSelectedItem()=="Bakso"){
            LbHargaMak3.setText("10000");
            
        }
        
        if (CbMakanan3.getSelectedItem()=="Soto"){
            LbHargaMak3.setText("15000");
        }
        
        if (CbMakanan3.getSelectedItem()=="Mie"){
            LbHargaMak3.setText("4000");
        }
        
        if (CbMakanan3.getSelectedItem()=="Capcay"){
            LbHargaMak3.setText("6000");
        }
        
        if (CbMakanan3.getSelectedItem() == ""){
            LbHargaMak3.setText("0");
        }
    }//GEN-LAST:event_CbMakanan3ActionPerformed

    private void CbMakanan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMakanan4ActionPerformed
        if (CbMakanan4.getSelectedItem()=="Bakso"){
            LbHargaMak4.setText("10000");
            
        }
        
        if (CbMakanan4.getSelectedItem()=="Soto"){
            LbHargaMak4.setText("15000");
        }
        
        if (CbMakanan4.getSelectedItem()=="Mie"){
            LbHargaMak4.setText("4000");
        }
        
        if (CbMakanan4.getSelectedItem()=="Capcay"){
            LbHargaMak4.setText("6000");
        }
        
        if (CbMakanan4.getSelectedItem() == ""){
            LbHargaMak4.setText("0");
        }
    }//GEN-LAST:event_CbMakanan4ActionPerformed

    private void CbMinuman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMinuman1ActionPerformed
         if (CbMinuman1.getSelectedItem()=="Es Teh"){
            LbHargaMin1.setText("1500");
        }
        
        if (CbMinuman1.getSelectedItem()=="Es Jeruk"){
            LbHargaMin1.setText("3000");
        }
        
        if (CbMinuman1.getSelectedItem()=="Air Mineral"){
            LbHargaMin1.setText("2500");
        }
        
        if (CbMinuman1.getSelectedItem()=="Es Kelapa"){
            LbHargaMin1.setText("6000");
        }
        
        if (CbMinuman1.getSelectedItem()== ""){
            LbHargaMin1.setText("0");
        }
    }//GEN-LAST:event_CbMinuman1ActionPerformed

    private void CbMinuman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMinuman2ActionPerformed
         if (CbMinuman2.getSelectedItem()=="Es Teh"){
            LbHargaMin2.setText("1500");
        }
        
        if (CbMinuman2.getSelectedItem()=="Es Jeruk"){
            LbHargaMin2.setText("3000");
        }
        
        if (CbMinuman2.getSelectedItem()=="Air Mineral"){
            LbHargaMin2.setText("2500");
        }
        
        if (CbMinuman2.getSelectedItem()=="Es Kelapa"){
            LbHargaMin2.setText("6000");
        }
        
        if (CbMinuman2.getSelectedItem()== ""){
            LbHargaMin2.setText("0");
        }
    }//GEN-LAST:event_CbMinuman2ActionPerformed

    private void CbMinuman3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMinuman3ActionPerformed
         if (CbMinuman3.getSelectedItem()=="Es Teh"){
            LbHargaMin3.setText("1500");
        }
        
        if (CbMinuman3.getSelectedItem()=="Es Jeruk"){
            LbHargaMin3.setText("3000");
        }
        
        if (CbMinuman3.getSelectedItem()=="Air Mineral"){
            LbHargaMin3.setText("2500");
        }
        
        if (CbMinuman3.getSelectedItem()=="Es Kelapa"){
            LbHargaMin3.setText("6000");
        }
        
        if (CbMinuman3.getSelectedItem()== ""){
            LbHargaMin3.setText("0");
        }
    }//GEN-LAST:event_CbMinuman3ActionPerformed

    private void CbMinuman4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbMinuman4ActionPerformed
         if (CbMinuman4.getSelectedItem()=="Es Teh"){
            LbHargaMin4.setText("1500");
        }
        
        if (CbMinuman4.getSelectedItem()=="Es Jeruk"){
            LbHargaMin4.setText("3000");
        }
        
        if (CbMinuman4.getSelectedItem()=="Air Mineral"){
            LbHargaMin4.setText("2500");
        }
        
        if (CbMinuman4.getSelectedItem()=="Es Kelapa"){
            LbHargaMin4.setText("6000");
        }
        
        if (CbMinuman4.getSelectedItem()== ""){
            LbHargaMin4.setText("0");
        }
    }//GEN-LAST:event_CbMinuman4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHitung;
    private javax.swing.JComboBox<String> CbMakanan;
    private javax.swing.JComboBox<String> CbMakanan1;
    private javax.swing.JComboBox<String> CbMakanan2;
    private javax.swing.JComboBox<String> CbMakanan3;
    private javax.swing.JComboBox<String> CbMakanan4;
    private javax.swing.JComboBox<String> CbMinuman;
    private javax.swing.JComboBox<String> CbMinuman1;
    private javax.swing.JComboBox<String> CbMinuman2;
    private javax.swing.JComboBox<String> CbMinuman3;
    private javax.swing.JComboBox<String> CbMinuman4;
    private javax.swing.JLabel LbHargaMak;
    private javax.swing.JLabel LbHargaMak1;
    private javax.swing.JLabel LbHargaMak2;
    private javax.swing.JLabel LbHargaMak3;
    private javax.swing.JLabel LbHargaMak4;
    private javax.swing.JLabel LbHargaMin;
    private javax.swing.JLabel LbHargaMin1;
    private javax.swing.JLabel LbHargaMin2;
    private javax.swing.JLabel LbHargaMin3;
    private javax.swing.JLabel LbHargaMin4;
    private javax.swing.JLabel LbHasil;
    private javax.swing.JTextField TfJumlahMak;
    private javax.swing.JTextField TfJumlahMak1;
    private javax.swing.JTextField TfJumlahMak2;
    private javax.swing.JTextField TfJumlahMak3;
    private javax.swing.JTextField TfJumlahMak4;
    private javax.swing.JTextField TfJumlahMin;
    private javax.swing.JTextField TfJumlahMin1;
    private javax.swing.JTextField TfJumlahMin2;
    private javax.swing.JTextField TfJumlahMin3;
    private javax.swing.JTextField TfJumlahMin4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
